apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: vibe-dev
servers: 1
agents: 2
kubeAPI:
  host: "0.0.0.0"
  hostIP: "127.0.0.1"
  hostPort: "6443"
image: rancher/k3s:v1.28.8-k3s1
ports:
  - port: 8000:80
    nodeFilters:
      - loadbalancer
  - port: 8443:443
    nodeFilters:
      - loadbalancer
  - port: 3306:30306
    nodeFilters:
      - loadbalancer
  - port: 6379:30379
    nodeFilters:
      - loadbalancer
volumes:
  # 使用用户主目录下的持久化存储，避免使用 /tmp 目录
  # /tmp 目录在系统重启时会被清空，可能导致数据丢失
  # 注意：k3d 需要绝对路径，脚本会在运行时替换 ${HOME}
  - volume: ${HOME}/.local/share/k3d/vibe-dev-storage:/var/lib/rancher/k3s/storage
registries:
  create:
    name: vibe-registry
    host: "0.0.0.0"
    hostPort: "5555"
options:
  k3d:
    wait: true
    timeout: "60s"
    disableLoadbalancer: false
  k3s:
    extraArgs: []
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
