CREATE TABLE toeic_ai_prompts (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    part2_prompt TEXT NOT NULL COMMENT 'TOEIC Part 2 AI提示词',
    part3_prompt TEXT NOT NULL COMMENT 'TOEIC Part 3 AI提示词',
    part4_prompt TEXT NOT NULL COMMENT 'TOEIC Part 4 AI提示词',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    INDEX idx_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='TOEIC AI提示词表';
