apiVersion: v1
kind: ConfigMap
metadata:
  name: vibe-api-config
  namespace: vibe-dev
  labels:
    app: vibe-api
    environment: development
data:
  config.yaml: |
    # Vibe Coding Starter k8s 部署配置
    server:
      host: "0.0.0.0"
      port: 8080
      mode: "debug"
      read_timeout: 30
      write_timeout: 30
      idle_timeout: 60

    # 数据库配置 - 连接到 k8s 内的 MySQL
    database:
      driver: "mysql"
      host: "mysql.vibe-dev.svc.cluster.local"
      port: 3306
      username: "vibe_user"
      password: "vibe_password"
      database: "vibe_coding_starter"
      charset: "utf8mb4"
      max_idle_conns: 10
      max_open_conns: 100
      conn_max_lifetime: 3600

    # 缓存配置 - 连接到 k8s 内的 Redis
    cache:
      driver: "redis"
      host: "redis.vibe-dev.svc.cluster.local"
      port: 6379
      password: ""
      database: 0
      pool_size: 10

    # 日志配置
    logger:
      level: "debug"
      format: "console"
      output: "stdout"
      filename: "logs/app.log"
      max_size: 100
      max_age: 30
      max_backups: 10
      compress: true

    # JWT 配置
    jwt:
      secret: "vibe-k8s-dev-secret-key-change-in-production"
      issuer: "vibe-coding-starter-k8s"
      expiration: 86400

    # AI 配置
    ai:
      enabled: false
      provider: "openai"
      api_key: ""
      model: "gpt-3.5-turbo"
      temperature: 0.7
      max_tokens: 1000

    # 文件上传配置
    upload:
      max_size: 10485760
      allowed_types:
        - "image/jpeg"
        - "image/png"
        - "image/gif"
        - "image/webp"
        - "application/pdf"
        - "text/plain"
      storage_type: "local"
      local_path: "uploads"

    # CORS 配置
    cors:
      allow_origins:
        - "http://localhost:3000"
        - "http://localhost:3001"
        - "http://api.vibe-dev.com:8000"
        - "http://api.vibe-dev.com"
      allow_methods:
        - "GET"
        - "POST"
        - "PUT"
        - "PATCH"
        - "DELETE"
        - "HEAD"
        - "OPTIONS"
      allow_headers:
        - "Origin"
        - "Content-Length"
        - "Content-Type"
        - "Authorization"
        - "X-Requested-With"
        - "X-Request-ID"
        - "X-API-Key"
      expose_headers:
        - "Content-Length"
        - "X-Request-ID"
        - "X-RateLimit-Limit"
        - "X-RateLimit-Remaining"
        - "X-RateLimit-Reset"
      allow_credentials: true
      max_age: 43200

    # 限流配置
    rate_limit:
      enabled: true
      requests_per_minute: 120
      burst: 20

    # 安全配置
    security:
      enable_https: false
      tls_cert_file: ""
      tls_key_file: ""
      hsts_max_age: 31536000
      hsts_include_subdomains: true
      hsts_preload: false
      csp_policy: "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self'; frame-ancestors 'none'"
      ip_whitelist: []
      ip_blacklist: []
      blocked_user_agents:
        - "sqlmap"
        - "nmap"
        - "nikto"
      max_request_size: 10485760
      request_timeout: 30
      bcrypt_cost: 12
      password_min_length: 6
      session_timeout: 3600
      max_login_attempts: 10
      lockout_duration: 300

    # 邮件配置
    email:
      enabled: false
      smtp_host: "smtp.gmail.com"
      smtp_port: 587
      username: ""
      password: ""
      from_email: "noreply@example.com"
      from_name: "Vibe Coding Starter k8s"

    # 监控配置
    monitoring:
      enabled: true
      metrics_path: "/metrics"
      health_path: "/health"

    # 开发配置
    development:
      auto_migrate: true
      seed_data: true
      debug_sql: true
      hot_reload: false

    # k8s 特定配置
    k8s:
      cluster_name: "vibe-dev"
      namespace: "vibe-dev"
      mysql_service: "mysql.vibe-dev.svc.cluster.local"
      mysql_port: 3306
      redis_service: "redis.vibe-dev.svc.cluster.local"
      redis_port: 6379

    # Kubernetes 配置
    kubernetes:
      config_path: "~/.kube/config"
      context: "k3d-vibe-dev"
      namespace: "vibe-dev"
